### ISSUE TITLE
Solarized LS_COLORS persist with set -U yimmy_solarized false

### ISSUE THREAD

**Issue by McAllaster** [oh-my-fish/theme-yimmy#3]
Since the LS_COLORS are being hardcoded as a part of the fish_prompt function without a check for `yimmy_solarized`, you see solarized colors even if you don't use solarized.

I would personally recommend defaulting to false, and only setting LS_COLORS or other solarized colors when set to true.

**Comment by jhillyerd** [comment]
Thanks for pointing this out, it does seem like a bug.
